# Generated by Django 6.0.4 on 2026-04-14 14:41

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('full_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='ФИО')),
                ('experience_level', models.CharField(choices=[('junior', 'Junior'), ('junior_plus', 'Junior+'), ('middle', 'Middle')], max_length=20, verbose_name='Уровень разработчика')),
                ('main_stack', models.CharField(choices=[('python', 'Python'), ('java', 'Java'), ('javascript', 'JavaScript / TypeScript'), ('go', 'Go'), ('csharp', 'C#'), ('other', 'Другой')], max_length=50, verbose_name='Основной стек')),
                ('target_position', models.CharField(blank=True, max_length=150, null=True, verbose_name='Целевая должность')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('simulation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('full', 'Полное интервью'), ('live_coding', 'Только Live-coding'), ('system_design', 'System Design')], max_length=20, verbose_name='Тип симуляции')),
                ('duration_minutes', models.IntegerField(default=45, verbose_name='Длительность (мин)')),
                ('stack', models.CharField(max_length=100, verbose_name='Стек технологий')),
                ('level', models.CharField(choices=[('junior', 'Junior'), ('junior_plus', 'Junior+'), ('middle', 'Middle')], max_length=20, verbose_name='Уровень сложности')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время начала')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Время завершения')),
                ('status', models.CharField(choices=[('in_progress', 'В процессе'), ('completed', 'Завершена'), ('aborted', 'Прервана')], default='in_progress', max_length=20, verbose_name='Статус')),
                ('overall_score', models.IntegerField(blank=True, null=True, verbose_name='Общая оценка (%)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Симуляция',
                'verbose_name_plural': 'Симуляции',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SimulationResult',
            fields=[
                ('result_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('overall_score', models.IntegerField(verbose_name='Общая оценка (%)')),
                ('category_scores', models.JSONField(verbose_name='Оценки по категориям')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('simulation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='core.simulation')),
            ],
            options={
                'verbose_name': 'Результат симуляции',
                'verbose_name_plural': 'Результаты симуляций',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weak_points', models.JSONField(verbose_name='Слабые места')),
                ('recommendations', models.JSONField(verbose_name='Рекомендации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='core.simulationresult')),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Обратные связи',
            },
        ),
    ]
