# Generated by Django 6.0.4 on 2026-04-15 12:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_roadmap_roadmaptask'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('question_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('full', 'Полное интервью'), ('live_coding', 'Только Live-coding'), ('system_design', 'System Design')], max_length=20, verbose_name='Тип симуляции')),
                ('level', models.CharField(choices=[('junior', 'Junior'), ('junior_plus', 'Junior+'), ('middle', 'Middle')], max_length=20, verbose_name='Уровень')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок вопроса')),
                ('description', models.TextField(verbose_name='Текст вопроса / задача')),
                ('expected_topics', models.JSONField(blank=True, null=True, verbose_name='Ожидаемые темы')),
                ('difficulty', models.IntegerField(default=5, verbose_name='Сложность (1-10)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Вопрос для интервью',
                'verbose_name_plural': 'Вопросы для интервью',
                'ordering': ['type', 'level', 'difficulty'],
            },
        ),
    ]
