# Generated by Django 6.0.4 on 2026-04-15 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_interviewquestion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interviewquestion',
            options={'ordering': ['type', 'level', 'stack', 'difficulty'], 'verbose_name': 'Вопрос для интервью', 'verbose_name_plural': 'Вопросы для интервью'},
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='stack',
            field=models.CharField(choices=[('python', 'Python'), ('java', 'Java'), ('javascript', 'JavaScript / TypeScript'), ('go', 'Go'), ('csharp', 'C#'), ('other', 'Другой')], default='other', max_length=50, verbose_name='Стек технологий'),
            preserve_default=False,
        ),
    ]
