# Generated by Django 6.0.4 on 2026-04-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_interviewquestion_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewquestion',
            name='expected_topics',
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='correct_answer',
            field=models.CharField(default='other', max_length=10, verbose_name='Правильный вариант (A, B, C или D)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='options',
            field=models.JSONField(default=list, verbose_name='Варианты ответов (A, B, C, D)'),
        ),
        migrations.AlterField(
            model_name='interviewquestion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='interviewquestion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
